### ISSUE TITLE
请问 react-native-xiaoshu 有开源的项目地址吗？

### ISSUE THREAD

**Issue by catericy** [onlyling/xant#5]
[github.com/hjfruit/react-native-xiaoshu](https://github.com/hjfruit/react-native-xiaoshu) 仓库地址 404

**Comment by onlyling** [comment]
文档地址：https://hjfruit.github.io/xiaoshu-doc/

源代码仓库暂时没有公开，可以通过 NPM + [RunKit](https://runkit.com/) 浏览源码，访问地址：https://npm.runkit.com/%40fruits-chain%2Freact-native-xiaoshu

**Comment by catericy** [comment]
thx
