### ISSUE TITLE
安装xant后，引入组件报错

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [onlyling/xant#6]
![image](https://user-images.githubusercontent.com/25316619/186295498-2b220c29-f4da-496a-b4dd-c694c4e634c6.png)

**Comment by onlyling** [comment]
很抱歉，xant 组件库没有发布到 npm，直接把原代码复制到项目，当做一组本地的组件使用。

如果操作麻烦，可以使用它的同胞兄弟组件库[@fruits-chain/react-native-xiaoshu](https://www.npmjs.com/package/@fruits-chain/react-native-xiaoshu)。

**Comment by jiaoxiaoyuan** [comment]
好的，非常感谢
